apiVersion: v1
kind: Service
metadata:
  labels:
    app: &ai-n-service ai-n-service
  name: *ai-n-service
spec:
  type: ClusterIP
  selector:
    app: *ai-n-service
  ports:
    - name: api
      port: 80
      protocol: TCP
      targetPort: api
